
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package plizik.bgm.init;

import plizik.bgm.item.WaterItem;
import plizik.bgm.item.VoidblockItem;
import plizik.bgm.item.SweetpotatoItem;
import plizik.bgm.item.LeatherItem;
import plizik.bgm.item.LavaItem;
import plizik.bgm.item.IronARMORItem;
import plizik.bgm.item.BreadItem;
import plizik.bgm.item.BookItem;
import plizik.bgm.item.BlazerodItem;
import plizik.bgm.item.BeefItem;
import plizik.bgm.item.AmethystswordItem;
import plizik.bgm.item.AmethystpickaxeItem;
import plizik.bgm.item.AmethysthoeItem;
import plizik.bgm.item.AmethystaxeItem;
import plizik.bgm.item.AmethystItem;
import plizik.bgm.BgmMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

public class BgmModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, BgmMod.MODID);
	public static final RegistryObject<Item> AIRWALL = block(BgmModBlocks.AIRWALL, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> BEACON = block(BgmModBlocks.BEACON, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> BEDROCK = block(BgmModBlocks.BEDROCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> BONEBLOCK = block(BgmModBlocks.BONEBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> BOOKSHELF = block(BgmModBlocks.BOOKSHELF, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CLAY = block(BgmModBlocks.CLAY, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> COALBLOCK = block(BgmModBlocks.COALBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> COALORE = block(BgmModBlocks.COALORE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> MOSSYCOBBLESTONE = block(BgmModBlocks.MOSSYCOBBLESTONE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> COMMANDBLOCK = block(BgmModBlocks.COMMANDBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEBLACK = block(BgmModBlocks.CONCRETEBLACK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEBLUE = block(BgmModBlocks.CONCRETEBLUE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEBROWN = block(BgmModBlocks.CONCRETEBROWN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETECYAN = block(BgmModBlocks.CONCRETECYAN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEGRAY = block(BgmModBlocks.CONCRETEGRAY, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEGREEN = block(BgmModBlocks.CONCRETEGREEN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETELIGHTBLUE = block(BgmModBlocks.CONCRETELIGHTBLUE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETELIME = block(BgmModBlocks.CONCRETELIME, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEMAGENTA = block(BgmModBlocks.CONCRETEMAGENTA, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEORANGE = block(BgmModBlocks.CONCRETEORANGE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEPINK = block(BgmModBlocks.CONCRETEPINK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEPURPLE = block(BgmModBlocks.CONCRETEPURPLE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETERED = block(BgmModBlocks.CONCRETERED, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETESILVER = block(BgmModBlocks.CONCRETESILVER, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEWHITE = block(BgmModBlocks.CONCRETEWHITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CONCRETEYELLOW = block(BgmModBlocks.CONCRETEYELLOW, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLWHITE = block(BgmModBlocks.WOOLWHITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> GLASS = block(BgmModBlocks.GLASS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> DIAMONDBLOCK = block(BgmModBlocks.DIAMONDBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> DIAMONDORE = block(BgmModBlocks.DIAMONDORE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> DIRTOLD = block(BgmModBlocks.DIRTOLD, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> EMERALDBLOCK = block(BgmModBlocks.EMERALDBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> EMERALDORE = block(BgmModBlocks.EMERALDORE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> ENCHANTINGTABLE = block(BgmModBlocks.ENCHANTINGTABLE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> ENDFRAME = block(BgmModBlocks.ENDFRAME, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> GLASSPANE = block(BgmModBlocks.GLASSPANE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> GLOWSTONE = block(BgmModBlocks.GLOWSTONE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> GOLDBLOCK = block(BgmModBlocks.GOLDBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> GOLDORE = block(BgmModBlocks.GOLDORE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> GRAVEL = block(BgmModBlocks.GRAVEL, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAY = block(BgmModBlocks.HARDENEDCLAY, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYBLACK = block(BgmModBlocks.HARDENEDCLAYBLACK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYBLUE = block(BgmModBlocks.HARDENEDCLAYBLUE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYBROWN = block(BgmModBlocks.HARDENEDCLAYBROWN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYCYAN = block(BgmModBlocks.HARDENEDCLAYCYAN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYGRAY = block(BgmModBlocks.HARDENEDCLAYGRAY, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYGREEN = block(BgmModBlocks.HARDENEDCLAYGREEN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYLIGHTBLUE = block(BgmModBlocks.HARDENEDCLAYLIGHTBLUE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYLIME = block(BgmModBlocks.HARDENEDCLAYLIME, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYMAGENTA = block(BgmModBlocks.HARDENEDCLAYMAGENTA, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYORANGE = block(BgmModBlocks.HARDENEDCLAYORANGE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYPINK = block(BgmModBlocks.HARDENEDCLAYPINK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYPURPLE = block(BgmModBlocks.HARDENEDCLAYPURPLE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYRED = block(BgmModBlocks.HARDENEDCLAYRED, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYSILVER = block(BgmModBlocks.HARDENEDCLAYSILVER, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYWHITE = block(BgmModBlocks.HARDENEDCLAYWHITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HARDENEDCLAYYELLOW = block(BgmModBlocks.HARDENEDCLAYYELLOW, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> HAYBLOCK = block(BgmModBlocks.HAYBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> ICE = block(BgmModBlocks.ICE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> PACKEDICE = block(BgmModBlocks.PACKEDICE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> IRONBAR = block(BgmModBlocks.IRONBAR, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> IRONBLOCK = block(BgmModBlocks.IRONBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> IRONORE = block(BgmModBlocks.IRONORE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> JUKEBOX = block(BgmModBlocks.JUKEBOX, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> LADDER = block(BgmModBlocks.LADDER, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> LAPISBLOCK = block(BgmModBlocks.LAPISBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> DARKOAKLOG = block(BgmModBlocks.DARKOAKLOG, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> BIRCHLOG = block(BgmModBlocks.BIRCHLOG, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> JUNGLELOG = block(BgmModBlocks.JUNGLELOG, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> OAKLOG = block(BgmModBlocks.OAKLOG, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SPRUCELOG = block(BgmModBlocks.SPRUCELOG, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> MAGMA = block(BgmModBlocks.MAGMA, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> MELON = block(BgmModBlocks.MELON, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> MOBSPAWNER = block(BgmModBlocks.MOBSPAWNER, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> MUSHROOMSTEM = block(BgmModBlocks.MUSHROOMSTEM, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> BROWNMUSHROOM = block(BgmModBlocks.BROWNMUSHROOM, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> REDMUSHROOM = block(BgmModBlocks.REDMUSHROOM, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> MYCELIUM = block(BgmModBlocks.MYCELIUM, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> NETHERBRICK = block(BgmModBlocks.NETHERBRICK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> NETHERRACK = block(BgmModBlocks.NETHERRACK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> NOTEBLOCK = block(BgmModBlocks.NOTEBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> OBSIDIAN = block(BgmModBlocks.OBSIDIAN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> PISTON = block(BgmModBlocks.PISTON, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> BIGOAKPLANKS = block(BgmModBlocks.BIGOAKPLANKS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> BIRCHPLANKS = block(BgmModBlocks.BIRCHPLANKS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> JUNGLEPLANKS = block(BgmModBlocks.JUNGLEPLANKS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> OAKPLANKS = block(BgmModBlocks.OAKPLANKS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SPRUCEPLANKS = block(BgmModBlocks.SPRUCEPLANKS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> PRISMARINE = block(BgmModBlocks.PRISMARINE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> PRISMARINEBRICKS = block(BgmModBlocks.PRISMARINEBRICKS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> DARKPRISMARINE = block(BgmModBlocks.DARKPRISMARINE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> PUMPKIN = block(BgmModBlocks.PUMPKIN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> PURPLEBLOCK = block(BgmModBlocks.PURPLEBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> PURPLEPILLAR = block(BgmModBlocks.PURPLEPILLAR, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> QUARTZBLOCK = block(BgmModBlocks.QUARTZBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> QUARTZPILLAR = block(BgmModBlocks.QUARTZPILLAR, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> QUARTZORE = block(BgmModBlocks.QUARTZORE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> NETHERBRICKRED = block(BgmModBlocks.NETHERBRICKRED, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> REDSAND = block(BgmModBlocks.REDSAND, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> REDSANDSTONE = block(BgmModBlocks.REDSANDSTONE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> REDSANDSTONECARVED = block(BgmModBlocks.REDSANDSTONECARVED, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> REDSTONEBLOCK = block(BgmModBlocks.REDSTONEBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> REDSTONELAMP = block(BgmModBlocks.REDSTONELAMP, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> REDSTONEORE = block(BgmModBlocks.REDSTONEORE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> REDSTONETORCH = block(BgmModBlocks.REDSTONETORCH, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SUGARCANE = block(BgmModBlocks.SUGARCANE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SAND = block(BgmModBlocks.SAND, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SANDSTONE = block(BgmModBlocks.SANDSTONE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SANDSTONESMOOTH = block(BgmModBlocks.SANDSTONESMOOTH, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SEALANTERN = block(BgmModBlocks.SEALANTERN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKER = block(BgmModBlocks.SHULKER, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERBLACK = block(BgmModBlocks.SHULKERBLACK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERBLUE = block(BgmModBlocks.SHULKERBLUE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERBROWN = block(BgmModBlocks.SHULKERBROWN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERCYAN = block(BgmModBlocks.SHULKERCYAN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERGRAY = block(BgmModBlocks.SHULKERGRAY, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERGREEN = block(BgmModBlocks.SHULKERGREEN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERLIGHTBLUE = block(BgmModBlocks.SHULKERLIGHTBLUE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERLIME = block(BgmModBlocks.SHULKERLIME, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERMAGENTA = block(BgmModBlocks.SHULKERMAGENTA, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERORANGE = block(BgmModBlocks.SHULKERORANGE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERPINK = block(BgmModBlocks.SHULKERPINK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERRED = block(BgmModBlocks.SHULKERRED, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERSILVER = block(BgmModBlocks.SHULKERSILVER, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERWHITE = block(BgmModBlocks.SHULKERWHITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SHULKERYELLOW = block(BgmModBlocks.SHULKERYELLOW, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SLIMEBLOCK = block(BgmModBlocks.SLIMEBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SNOWBLOCK = block(BgmModBlocks.SNOWBLOCK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SOULSAND = block(BgmModBlocks.SOULSAND, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SPONGE = block(BgmModBlocks.SPONGE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WETSPONGE = block(BgmModBlocks.WETSPONGE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> STONE = block(BgmModBlocks.STONE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> STONEGRANITE = block(BgmModBlocks.STONEGRANITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> POLISHEDGRANITE = block(BgmModBlocks.POLISHEDGRANITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> ANDESITE = block(BgmModBlocks.ANDESITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> POLISHEDANDESITE = block(BgmModBlocks.POLISHEDANDESITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> POLISHEDSTONE = block(BgmModBlocks.POLISHEDSTONE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> POLISHEDANDESITE_2 = block(BgmModBlocks.POLISHEDANDESITE_2, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> DIORITE = block(BgmModBlocks.DIORITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SMOOTHDIORITE = block(BgmModBlocks.SMOOTHDIORITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> SMOOTHGRANITE = block(BgmModBlocks.SMOOTHGRANITE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> STONESLAB = block(BgmModBlocks.STONESLAB, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> STONEBRICKS = block(BgmModBlocks.STONEBRICKS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CARVEDSTONEBRICKS = block(BgmModBlocks.CARVEDSTONEBRICKS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CRACKEDSTONEBRICKS = block(BgmModBlocks.CRACKEDSTONEBRICKS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> MOSSYSTONEBRICKS = block(BgmModBlocks.MOSSYSTONEBRICKS, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> TNT = block(BgmModBlocks.TNT, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> TORCH = block(BgmModBlocks.TORCH, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> TRAPDOOR = block(BgmModBlocks.TRAPDOOR, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WEB = block(BgmModBlocks.WEB, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLBLACK = block(BgmModBlocks.WOOLBLACK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLBLUE = block(BgmModBlocks.WOOLBLUE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLBROWN = block(BgmModBlocks.WOOLBROWN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLCYAN = block(BgmModBlocks.WOOLCYAN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLGRAY = block(BgmModBlocks.WOOLGRAY, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLGREEN = block(BgmModBlocks.WOOLGREEN, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLLIGHTBLUE = block(BgmModBlocks.WOOLLIGHTBLUE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLLIME = block(BgmModBlocks.WOOLLIME, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLMAGENTA = block(BgmModBlocks.WOOLMAGENTA, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLORANGE = block(BgmModBlocks.WOOLORANGE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLPINK = block(BgmModBlocks.WOOLPINK, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLPURPLE = block(BgmModBlocks.WOOLPURPLE, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLRED = block(BgmModBlocks.WOOLRED, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLSILVER = block(BgmModBlocks.WOOLSILVER, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> WOOLYELLOW = block(BgmModBlocks.WOOLYELLOW, BgmModTabs.TAB_BGM_BLOCKS);
	public static final RegistryObject<Item> CHRISTMASBLOCKWHITE = block(BgmModBlocks.CHRISTMASBLOCKWHITE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKORANGE = block(BgmModBlocks.CHRISTMASBLOCKORANGE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKMAGENTA = block(BgmModBlocks.CHRISTMASBLOCKMAGENTA, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKLIGHTBLUE = block(BgmModBlocks.CHRISTMASBLOCKLIGHTBLUE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKYELLOW = block(BgmModBlocks.CHRISTMASBLOCKYELLOW, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKLIME = block(BgmModBlocks.CHRISTMASBLOCKLIME, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKPINK = block(BgmModBlocks.CHRISTMASBLOCKPINK, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKGRAY = block(BgmModBlocks.CHRISTMASBLOCKGRAY, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKLIGHTGRAY = block(BgmModBlocks.CHRISTMASBLOCKLIGHTGRAY, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKCYAN = block(BgmModBlocks.CHRISTMASBLOCKCYAN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKPURPLE = block(BgmModBlocks.CHRISTMASBLOCKPURPLE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKBLUE = block(BgmModBlocks.CHRISTMASBLOCKBLUE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKBROWN = block(BgmModBlocks.CHRISTMASBLOCKBROWN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKGREEN = block(BgmModBlocks.CHRISTMASBLOCKGREEN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKRED = block(BgmModBlocks.CHRISTMASBLOCKRED, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASBLOCKBLACK = block(BgmModBlocks.CHRISTMASBLOCKBLACK, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREWHITE = block(BgmModBlocks.CHRISTMASPUREWHITE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREORANGE = block(BgmModBlocks.CHRISTMASPUREORANGE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREMAGENTA = block(BgmModBlocks.CHRISTMASPUREMAGENTA, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPURELIGHTBLUE = block(BgmModBlocks.CHRISTMASPURELIGHTBLUE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREYELLOW = block(BgmModBlocks.CHRISTMASPUREYELLOW, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPURELIME = block(BgmModBlocks.CHRISTMASPURELIME, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREPINK = block(BgmModBlocks.CHRISTMASPUREPINK, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREGRAY = block(BgmModBlocks.CHRISTMASPUREGRAY, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPURELIGHTGRAY = block(BgmModBlocks.CHRISTMASPURELIGHTGRAY, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPURECYAN = block(BgmModBlocks.CHRISTMASPURECYAN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREPURPLE = block(BgmModBlocks.CHRISTMASPUREPURPLE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREBLUE = block(BgmModBlocks.CHRISTMASPUREBLUE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREBROWN = block(BgmModBlocks.CHRISTMASPUREBROWN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREGREEN = block(BgmModBlocks.CHRISTMASPUREGREEN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPURERED = block(BgmModBlocks.CHRISTMASPURERED, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CHRISTMASPUREBLACK = block(BgmModBlocks.CHRISTMASPUREBLACK, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> COBBLESTONE = block(BgmModBlocks.COBBLESTONE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> CRAFTING_TABLE = block(BgmModBlocks.CRAFTING_TABLE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> SKYBLOCKDIRT = block(BgmModBlocks.SKYBLOCKDIRT, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> FURNACE = block(BgmModBlocks.FURNACE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSBLACK = block(BgmModBlocks.GLASSBLACK, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSBLUE = block(BgmModBlocks.GLASSBLUE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSBROWN = block(BgmModBlocks.GLASSBROWN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSCYAN = block(BgmModBlocks.GLASSCYAN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSGRAY = block(BgmModBlocks.GLASSGRAY, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSGREEN = block(BgmModBlocks.GLASSGREEN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSLIGHTBLUE = block(BgmModBlocks.GLASSLIGHTBLUE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSLIME = block(BgmModBlocks.GLASSLIME, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSMAGENTA = block(BgmModBlocks.GLASSMAGENTA, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSNEW = block(BgmModBlocks.GLASSNEW, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSORANGE = block(BgmModBlocks.GLASSORANGE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPINK = block(BgmModBlocks.GLASSPINK, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPURPLE = block(BgmModBlocks.GLASSPURPLE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSRED = block(BgmModBlocks.GLASSRED, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSSILVER = block(BgmModBlocks.GLASSSILVER, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSWHITE = block(BgmModBlocks.GLASSWHITE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSYELLOW = block(BgmModBlocks.GLASSYELLOW, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEBLACK = block(BgmModBlocks.GLASSPANEBLACK, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEBLUE = block(BgmModBlocks.GLASSPANEBLUE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEBROWN = block(BgmModBlocks.GLASSPANEBROWN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANECYAN = block(BgmModBlocks.GLASSPANECYAN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEGRAY = block(BgmModBlocks.GLASSPANEGRAY, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEGREEN = block(BgmModBlocks.GLASSPANEGREEN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANELIGHTBLUE = block(BgmModBlocks.GLASSPANELIGHTBLUE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANELIME = block(BgmModBlocks.GLASSPANELIME, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEMAGENTA = block(BgmModBlocks.GLASSPANEMAGENTA, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEORANGE = block(BgmModBlocks.GLASSPANEORANGE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEPINK = block(BgmModBlocks.GLASSPANEPINK, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEPURPLE = block(BgmModBlocks.GLASSPANEPURPLE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANERED = block(BgmModBlocks.GLASSPANERED, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANESILVER = block(BgmModBlocks.GLASSPANESILVER, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEWHITE = block(BgmModBlocks.GLASSPANEWHITE, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GLASSPANEYELLOW = block(BgmModBlocks.GLASSPANEYELLOW, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> SKYBLOCKGRASS = block(BgmModBlocks.SKYBLOCKGRASS, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GOLDBARS = block(BgmModBlocks.GOLDBARS, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> MONEYBLOCK = block(BgmModBlocks.MONEYBLOCK, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GIFTGREEN = block(BgmModBlocks.GIFTGREEN, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GIFTRED = block(BgmModBlocks.GIFTRED, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> GIFTYELLOW = block(BgmModBlocks.GIFTYELLOW, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> STARBLOCK = block(BgmModBlocks.STARBLOCK, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> SILVERBAR = block(BgmModBlocks.SILVERBAR, BgmModTabs.TAB_BGM_SKYBLOCK);
	public static final RegistryObject<Item> COARSEDIRT = block(BgmModBlocks.COARSEDIRT, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> GREENGIFT = block(BgmModBlocks.GREENGIFT, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> REDGIFT = block(BgmModBlocks.REDGIFT, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> YELLOWGIFT = block(BgmModBlocks.YELLOWGIFT, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERBLACK = block(BgmModBlocks.CONCRETEPOWDERBLACK, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERBLUE = block(BgmModBlocks.CONCRETEPOWDERBLUE, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERBROWN = block(BgmModBlocks.CONCRETEPOWDERBROWN, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERCYAN = block(BgmModBlocks.CONCRETEPOWDERCYAN, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERGRAY = block(BgmModBlocks.CONCRETEPOWDERGRAY, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERGREEN = block(BgmModBlocks.CONCRETEPOWDERGREEN, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERLIGHTBLUE = block(BgmModBlocks.CONCRETEPOWDERLIGHTBLUE, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERLIME = block(BgmModBlocks.CONCRETEPOWDERLIME, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERMAGENTA = block(BgmModBlocks.CONCRETEPOWDERMAGENTA, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERORANGE = block(BgmModBlocks.CONCRETEPOWDERORANGE, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERPINK = block(BgmModBlocks.CONCRETEPOWDERPINK, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERRED = block(BgmModBlocks.CONCRETEPOWDERRED, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERPURPLE = block(BgmModBlocks.CONCRETEPOWDERPURPLE, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERSILVER = block(BgmModBlocks.CONCRETEPOWDERSILVER, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERWHITE = block(BgmModBlocks.CONCRETEPOWDERWHITE, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CONCRETEPOWDERYELLOW = block(BgmModBlocks.CONCRETEPOWDERYELLOW, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> DIRTOLDPODZOL = block(BgmModBlocks.DIRTOLDPODZOL, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> ENDBRICK = block(BgmModBlocks.ENDBRICK, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> GLASSPURPLE_2 = block(BgmModBlocks.GLASSPURPLE_2, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> GLASSSILVER_2 = block(BgmModBlocks.GLASSSILVER_2, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> HELLGLOWSTONE = block(BgmModBlocks.HELLGLOWSTONE, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> OLDDIRTPATH = block(BgmModBlocks.OLDDIRTPATH, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> IRONTRAPDOOR = block(BgmModBlocks.IRONTRAPDOOR, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> JUNGLELOG_2 = block(BgmModBlocks.JUNGLELOG_2, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> LUCKYBLOCKSTRANGE = block(BgmModBlocks.LUCKYBLOCKSTRANGE, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> NETHERWARTBLOCK = block(BgmModBlocks.NETHERWARTBLOCK, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> OBSERVER = block(BgmModBlocks.OBSERVER, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> STICKYPISTON = block(BgmModBlocks.STICKYPISTON, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> ROUGHPRISMARINE = block(BgmModBlocks.ROUGHPRISMARINE, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> PUMPKINLIT = block(BgmModBlocks.PUMPKINLIT, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> REDSANDSTONECARVED_2 = block(BgmModBlocks.REDSANDSTONECARVED_2, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> REDSTONELAMP_2 = block(BgmModBlocks.REDSTONELAMP_2, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> CARPETROAD = block(BgmModBlocks.CARPETROAD, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> SANDSTONESMOOTH_2 = block(BgmModBlocks.SANDSTONESMOOTH_2, BgmModTabs.TAB_BG_MNOTADDED);
	public static final RegistryObject<Item> TOWER = block(BgmModBlocks.TOWER, BgmModTabs.TAB_BGM_BEDWARS);
	public static final RegistryObject<Item> WALLOFWOOL = block(BgmModBlocks.WALLOFWOOL, BgmModTabs.TAB_BGM_BEDWARS);
	public static final RegistryObject<Item> ENDSTONE = block(BgmModBlocks.ENDSTONE, BgmModTabs.TAB_BGM_BEDWARS);
	public static final RegistryObject<Item> BWDEFENCEGLASS = block(BgmModBlocks.BWDEFENCEGLASS, BgmModTabs.TAB_BGM_BEDWARS);
	public static final RegistryObject<Item> BEDWARSSPONGE = block(BgmModBlocks.BEDWARSSPONGE, BgmModTabs.TAB_BGM_BEDWARS);
	public static final RegistryObject<Item> LUCKYBLOCKARMOR = block(BgmModBlocks.LUCKYBLOCKARMOR, BgmModTabs.TAB_BGM_ITEMS);
	public static final RegistryObject<Item> LUCKYBLOCKEVENT = block(BgmModBlocks.LUCKYBLOCKEVENT, BgmModTabs.TAB_BGM_ITEMS);
	public static final RegistryObject<Item> LUCKYBLOCKWEAPON = block(BgmModBlocks.LUCKYBLOCKWEAPON, BgmModTabs.TAB_BGM_ITEMS);
	public static final RegistryObject<Item> LUCKYBLOCKPROP = block(BgmModBlocks.LUCKYBLOCKPROP, BgmModTabs.TAB_BGM_ITEMS);
	public static final RegistryObject<Item> VOIDBLOCK = REGISTRY.register("voidblock", () -> new VoidblockItem());
	public static final RegistryObject<Item> AMETHYSTAXE = REGISTRY.register("amethystaxe", () -> new AmethystaxeItem());
	public static final RegistryObject<Item> AMETHYSTHOE = REGISTRY.register("amethysthoe", () -> new AmethysthoeItem());
	public static final RegistryObject<Item> AMETHYSTPICKAXE = REGISTRY.register("amethystpickaxe", () -> new AmethystpickaxeItem());
	public static final RegistryObject<Item> BROWNMUSHROOMSMALL = block(BgmModBlocks.BROWNMUSHROOMSMALL, BgmModTabs.TAB_BGMPLANTS);
	public static final RegistryObject<Item> REDMUSHROOMSMALL = block(BgmModBlocks.REDMUSHROOMSMALL, BgmModTabs.TAB_BGMPLANTS);
	public static final RegistryObject<Item> OBSIDIANBEDWARS = block(BgmModBlocks.OBSIDIANBEDWARS, BgmModTabs.TAB_BGMPLANTS);
	public static final RegistryObject<Item> VINE = block(BgmModBlocks.VINE, BgmModTabs.TAB_BGMPLANTS);
	public static final RegistryObject<Item> MOVINGPISTON = block(BgmModBlocks.MOVINGPISTON, null);
	public static final RegistryObject<Item> REDSTONELAMPON = block(BgmModBlocks.REDSTONELAMPON, null);
	public static final RegistryObject<Item> AMETHYST_HELMET = REGISTRY.register("amethyst_helmet", () -> new AmethystItem.Helmet());
	public static final RegistryObject<Item> AMETHYST_CHESTPLATE = REGISTRY.register("amethyst_chestplate", () -> new AmethystItem.Chestplate());
	public static final RegistryObject<Item> AMETHYST_LEGGINGS = REGISTRY.register("amethyst_leggings", () -> new AmethystItem.Leggings());
	public static final RegistryObject<Item> AMETHYST_BOOTS = REGISTRY.register("amethyst_boots", () -> new AmethystItem.Boots());
	public static final RegistryObject<Item> LEATHER_HELMET = REGISTRY.register("leather_helmet", () -> new LeatherItem.Helmet());
	public static final RegistryObject<Item> LEATHER_CHESTPLATE = REGISTRY.register("leather_chestplate", () -> new LeatherItem.Chestplate());
	public static final RegistryObject<Item> LEATHER_LEGGINGS = REGISTRY.register("leather_leggings", () -> new LeatherItem.Leggings());
	public static final RegistryObject<Item> LEATHER_BOOTS = REGISTRY.register("leather_boots", () -> new LeatherItem.Boots());
	public static final RegistryObject<Item> IRON_ARMOR_HELMET = REGISTRY.register("iron_armor_helmet", () -> new IronARMORItem.Helmet());
	public static final RegistryObject<Item> IRON_ARMOR_CHESTPLATE = REGISTRY.register("iron_armor_chestplate", () -> new IronARMORItem.Chestplate());
	public static final RegistryObject<Item> IRON_ARMOR_LEGGINGS = REGISTRY.register("iron_armor_leggings", () -> new IronARMORItem.Leggings());
	public static final RegistryObject<Item> IRON_ARMOR_BOOTS = REGISTRY.register("iron_armor_boots", () -> new IronARMORItem.Boots());
	public static final RegistryObject<Item> SWEETPOTATO = REGISTRY.register("sweetpotato", () -> new SweetpotatoItem());
	public static final RegistryObject<Item> BEEF = REGISTRY.register("beef", () -> new BeefItem());
	public static final RegistryObject<Item> BREAD = REGISTRY.register("bread", () -> new BreadItem());
	public static final RegistryObject<Item> WATER_BUCKET = REGISTRY.register("water_bucket", () -> new WaterItem());
	public static final RegistryObject<Item> LAVA_BUCKET = REGISTRY.register("lava_bucket", () -> new LavaItem());
	public static final RegistryObject<Item> BLAZEROD = REGISTRY.register("blazerod", () -> new BlazerodItem());
	public static final RegistryObject<Item> BOOK = REGISTRY.register("book", () -> new BookItem());
	public static final RegistryObject<Item> AMETHYSTSWORD = REGISTRY.register("amethystsword", () -> new AmethystswordItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
